language: node_js
node_js:
  - "6"
  

script:
  - yarn install
  - yarn test

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always
